name: Crypto Bot Scanner

on:
  schedule:
    # Her 15 dakikada bir çalıştır (00, 15, 30, 45 geçe)
    - cron: '5,20,35,50 * * * *'
  workflow_dispatch: # Manuel tetikleme butonu ekler (Test için)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python to resolve dependencies
        uses: actions/setup-python@v4
        with:
          # Kütüphanelerin istediği minimum sürümü kullanıyoruz
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Trading Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${ -5098978804 }}
        run: python main.py
