name: Crypto Bot Scanner

on:
  schedule:
    # Sunucu yoğunluğunu atlatmak için her saatin 5, 20, 35 ve 50. dakikalarında çalışır.
    - cron: '5,20,35,50 * * * *'
  workflow_dispatch: # Manuel tetikleme butonu (Test için)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python to resolve dependencies
        uses: actions/setup-python@v4
        with:
          # Kütüphane hatalarını önlemek için Python 3.12 kullanıyoruz
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Trading Bot
        env:
          # BURASI DÜZELTİLDİ: $ ve {{ arasında boşluk yok!
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
